pipeline {
    agent any
    
    environment {
        AWS_REGION     = "us-east-2"
        IMAGE_REPO     = "php-ecommerce-app"
        ECR_URL        = "681504525746.dkr.ecr.us-east-2.amazonaws.com/${IMAGE_REPO}"
    }
    
    stages {
        stage('Pre-Build: PHP Linting') {
            steps {
                sh "find ./app -name '*.php' -print0 | xargs -0 -n1 php -l"
            }
        }
        
        stage('Docker Build') {
            steps {
                sh "docker build -t ${IMAGE_REPO}:${GIT_COMMIT} ./app"
            }
        }
        # stage
        stage('Security Scan') {
            steps {
                sh "trivy image --severity HIGH,CRITICAL ${IMAGE_REPO}:${GIT_COMMIT}"
            }
        }
        
        stage('Push to AWS ECR') {
            steps {
                sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin 681504525746.dkr.ecr.${AWS_REGION}.amazonaws.com"
                
                sh "docker tag ${IMAGE_REPO}:${GIT_COMMIT} ${ECR_URL}:${GIT_COMMIT}"
                sh "docker tag ${IMAGE_REPO}:${GIT_COMMIT} ${ECR_URL}:latest"
                
                sh "docker push ${ECR_URL}:${GIT_COMMIT}"
                sh "docker push ${ECR_URL}:latest"
            }
        }
        
        stage('Deploy to App EC2 (via SSM)') {
            steps {
                script {
                    def INSTANCE_ID = sh(script: "aws ec2 describe-instances --region ${AWS_REGION} --filters 'Name=tag:Name,Values=web-app' 'Name=instance-state-name,Values=running' --query 'Reservations[0].Instances[0].InstanceId' --output text", returnStdout: true).trim()

                    sh """
                    aws ssm send-command \
                        --region ${AWS_REGION} \
                        --instance-ids "${INSTANCE_ID}" \
                        --document-name "AWS-RunShellScript" \
                        --parameters 'commands=[
                            "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com",
                            "docker pull ${ECR_URL}:latest",
                            "docker stop php-ecommerce-app || true",
                            "docker rm php-ecommerce-app || true",
                            "docker run -d --name php-ecommerce-app -p 80:80 --env-file /etc/ecommerce.env --log-driver=awslogs --log-opt awslogs-region=${AWS_REGION} --log-opt awslogs-group=/ec2/php-ecommerce-app ${ECR_URL}:latest"
                        ]'
                    """
                }
            }
        }
    
    post {
        always {
            sh "docker system prune -af --volumes"
        }
        failure {
            echo "Pipeline failed! Check the logs."
        }
        success {
            echo "Deployment successful via AWS SSM!"
        }
    }
}